url: http://www.qnnsafes.com

name: QNNSafe

title: QNNSafe

description: QNNSafe

keywords: QNNSafe

image_cdn: http://test.html9.com

exclude: ['README.md', 'LICENSE']

markdown: rdiscount

permalink: :categories/:title.html

categories_for_products: [
  ["hotel-safes",              "Hotel Safes"],
  ["gun-safes",                "Gun Safes"],
  ["commercial-safes",         "Commercial Safes"],
  ["fireproof-safes",          "Fireproof Safes"],
  ["filing-cabinet-safes",     "Filing Cabinet Safes"],
  ["burglary-and-fire-safes",  "Burglary and Fire Safes"],
  ["lockers",                  "Lockers"],
  ["wall-safes",               "Wall Safes"],
  ["floor-safes",              "Floor Safes"],
  ["depository-safes",         "Depository Safes"],
  ["fingerprint-safes",        "Fingerprint Safes"],
  ["home-or-office-safes",     "Home or Office Safes"],
  ["new-safes",                "New Safes"],
]
